#!/usr/bin/env bash

progress-bar() {
	local i=$1
	local len=$2
	
	local perc_done=$((i * 100 / len))

	echo "processing $i/$len ($perc_done%)"
}

shopt -s globstar nullglob

echo 'finding files'
find . -name '*cache'

files=(./**/*cache)
len=${#files[@]}

echo "found $len files"

i=0
for file in "${files[@]}"; do
	progress-bar "$((i+1))" "$len"
	((i++))
done
